### PR TITLE
docs: fix README examples

### PR DESCRIPTION
**Pull request by aaarichter**
Changes:
- change order of `left` and `right` to reflect proper order (see https://developer.mozilla.org/en-US/docs/Web/CSS/inset) 
- add small css comment with original logical property to make it easier to grasp
- change order of `resize`, so the logical (and newer) css value is later
- add some spacing to js example

### CODE REVIEW

**Comment by Antonio-Laguna** [comment]
@aaarichter thanks a lot for your contribution. I think this makes a lot of sense. Thank you for catching the resize order which also matches what's being output by the library.

My only (nitpicky) concern is with the `css` highlighting. I understand this is mostly just CSS but pcss is actually highlighted and is consistent with the rest of the plugins.

**Comment by aaarichter** [comment]
@Antonio-Laguna 

> but pcss is actually highlighted and is consistent with the rest of the plugins.

I see. I was editing the markdown file in Webstorm IDE, which seems to lack pcss highlighting. 

I updated and force pushed the previous commit

**Comment by romainmenke** [comment]
@aaarichter This repo has been moved to https://github.com/csstools/postcss-plugins and will be archived soon.

Do you want to resubmit this PR there?
Would be great to improve the readme!

_If you don't have time we will try to update this as soon as possible._

**Comment by romainmenke** [comment]
@aaarichter We've updated the readme in the mono repo.
Thank you for your contribution!

**Pull request closed without merging**
